# Generated by Django 4.2.8 on 2026-03-04 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_add_foreign_keys'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='gpsposition',
            new_name='core_gpspos_bus_id_4cbf4b_idx',
            old_name='core_gpspos_bus_id_timestamp_idx',
        ),
        migrations.AddField(
            model_name='bus',
            name='modele',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='tarif_base',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='line',
            name='terminus_arrivee',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='line',
            name='terminus_depart',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacite',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='bus',
            name='numero_bankily',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='places_disponibles',
            field=models.IntegerField(default=30),
        ),
        migrations.AlterField(
            model_name='bus',
            name='statut',
            field=models.CharField(choices=[('ACTIF', 'Actif'), ('MAINTENANCE', 'En Maintenance'), ('REPOSE', 'Au Repos'), ('INACTIF', 'Inactif'), ('HORS_SERVICE', 'Hors Service')], default='ACTIF', max_length=20),
        ),
        migrations.AlterField(
            model_name='driver',
            name='adresse',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='driver',
            name='date_expiration_permis',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='numero_permis',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='line',
            name='heure_depart',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='line',
            name='heure_fin',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
