# Generated by Django 4.2.8 on 2026-03-04 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_model_fixes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bus',
            name='ligne',
        ),
        migrations.AddField(
            model_name='bus',
            name='lignes',
            field=models.ManyToManyField(blank=True, related_name='buses', to='core.line'),
        ),
    ]
