# Generated by Django 4.2.8 on 2026-03-05 03:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_report_reply_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitizenUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telephone', models.CharField(max_length=20, unique=True)),
                ('nom', models.CharField(max_length=100)),
                ('prenom', models.CharField(max_length=100)),
                ('nni', models.CharField(blank=True, max_length=30, null=True, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('statut', models.CharField(choices=[('ACTIF', 'Actif'), ('SUSPENDU', 'Suspendu'), ('INACTIF', 'Inactif')], default='ACTIF', max_length=20)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('derniere_connexion', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Citoyen',
                'verbose_name_plural': 'Citoyens',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='WalletTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type_transaction', models.CharField(choices=[('RECHARGE', 'Recharge'), ('PAIEMENT', 'Paiement trajet'), ('REMBOURSEMENT', 'Remboursement')], max_length=20)),
                ('statut', models.CharField(choices=[('EN_ATTENTE', 'En attente'), ('VALIDE', 'Validé'), ('REFUSE', 'Refusé')], default='EN_ATTENTE', max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('reference_bankily', models.CharField(blank=True, max_length=100)),
                ('photo_bankily', models.ImageField(blank=True, null=True, upload_to='wallet/bankily/')),
                ('valide_par', models.CharField(blank=True, max_length=100)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_validation', models.DateTimeField(blank=True, null=True)),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='core.citizenuser')),
            ],
            options={
                'verbose_name': 'Transaction Wallet',
                'ordering': ['-date_creation'],
            },
        ),
        migrations.CreateModel(
            name='WalletDriver',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('chauffeur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.driver')),
            ],
            options={
                'verbose_name': 'Wallet Chauffeur',
            },
        ),
        migrations.CreateModel(
            name='WalletCitizen',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
                ('citoyen', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='wallet', to='core.citizenuser')),
            ],
            options={
                'verbose_name': 'Wallet Citoyen',
            },
        ),
        migrations.CreateModel(
            name='CitizenTrip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('montant_paye', models.DecimalField(decimal_places=2, max_digits=10)),
                ('statut', models.CharField(choices=[('PAYE', 'Payé'), ('ANNULE', 'Annulé')], default='PAYE', max_length=20)),
                ('methode_paiement', models.CharField(default='WALLET', max_length=30)),
                ('date_paiement', models.DateTimeField(auto_now_add=True)),
                ('bus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.bus')),
                ('citoyen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajets', to='core.citizenuser')),
                ('ligne', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.line')),
                ('trajet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.trip')),
            ],
            options={
                'verbose_name': 'Trajet Citoyen',
                'ordering': ['-date_paiement'],
            },
        ),
    ]
