# Generated by Django 4.2.8 on 2026-03-05 13:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_citizen_wallet'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppWallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('date_mise_a_jour', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Wallet App MauriBus',
            },
        ),
        migrations.CreateModel(
            name='AppTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type_transaction', models.CharField(choices=[('COMMISSION', 'Commission trajet'), ('PAIEMENT_CHAUFFEUR', 'Paiement chauffeur'), ('RECHARGE_BANQUE', 'Recharge depuis banque')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('effectue_par', models.CharField(blank=True, max_length=100)),
                ('solde_avant', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('solde_apres', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('chauffeur', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='app_payments', to='core.driver')),
            ],
            options={
                'verbose_name': 'Transaction App Wallet',
                'ordering': ['-date_creation'],
            },
        ),
    ]
