# Generated by Django 4.2.8 on 2026-03-05 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_app_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='date_planifiee',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
